name: Experimental Tests

on: [push, pull_request]

jobs:

    # Test job
    pki-tests:
      # This job depends on the 'build' job and waits till it completes.
      # This job needs container to be started manually, as Github provided
      # container **does not** use /usr/bin/init as its ENTRYPOINT.
      name: Test contents of /usr/sbin
      runs-on: ubuntu-latest
      steps:
        - name: Print contents of /usr/sbin/init
          run: ls -la /usr/sbin/

        - name: Find the location of init
          run: which init
